# Generated by Django 5.2.4 on 2025-07-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam1', '0002_questions_delete_classtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
